
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum AbilityType
    {
        /// <summary>
        /// 通用技能
        /// </summary>
        COMMON = 1,
        /// <summary>
        /// 武器技能
        /// </summary>
        WEAPON = 2,
    }

} 

