
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// ai 参数
/// </summary>
public sealed partial class AiParamsBase : Luban.BeanBase
{
    public AiParamsBase(ByteBuf _buf) 
    {
        VisionRange = _buf.ReadInt();
        ThreatTime = _buf.ReadInt();
    }

    public static AiParamsBase DeserializeAiParamsBase(ByteBuf _buf)
    {
        return new AiParamsBase(_buf);
    }

    /// <summary>
    /// 警觉范围 / 视野范围（格子数，触发 Suspicious 的距离）
    /// </summary>
    public readonly int VisionRange;
    /// <summary>
    /// 警惕值（回合数，警觉状态持续时间，超时衰减）
    /// </summary>
    public readonly int ThreatTime;
   
    public const int __ID__ = -1732219937;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "VisionRange:" + VisionRange + ","
        + "ThreatTime:" + ThreatTime + ","
        + "}";
    }
}

}

