
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum AiPattern
    {
        /// <summary>
        /// 默认
        /// </summary>
        Default = 0,
        /// <summary>
        /// 召唤物1
        /// </summary>
        Summon = 1,
        /// <summary>
        /// 谨慎
        /// </summary>
        Cautious = 2,
        /// <summary>
        /// 群猎
        /// </summary>
        PackHunter = 3,
        /// <summary>
        /// 胆小
        /// </summary>
        Fleeing = 4,
    }

} 

