
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// AI策略专有参数 - 多态基类
/// </summary>
public abstract partial class AiStrategyParams : Luban.BeanBase
{
    public AiStrategyParams(ByteBuf _buf) 
    {
    }

    public static AiStrategyParams DeserializeAiStrategyParams(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case DefaultParams.__ID__: return new DefaultParams(_buf);
            case Summon1Params.__ID__: return new Summon1Params(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

