
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 等级表
/// </summary>
public partial class Data_LevelUp
{
    private readonly System.Collections.Generic.Dictionary<int, t_LevelUp> _dataMap;
    private readonly System.Collections.Generic.List<t_LevelUp> _dataList;
    
    public Data_LevelUp(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, t_LevelUp>();
        _dataList = new System.Collections.Generic.List<t_LevelUp>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            t_LevelUp _v;
            _v = t_LevelUp.Deserializet_LevelUp(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, t_LevelUp> DataMap => _dataMap;
    public System.Collections.Generic.List<t_LevelUp> DataList => _dataList;

    public t_LevelUp GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public t_LevelUp Get(int key) => _dataMap[key];
    public t_LevelUp this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

