
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// AI表
/// </summary>
public partial class Data_AI
{
    private readonly System.Collections.Generic.Dictionary<int, t_AI> _dataMap;
    private readonly System.Collections.Generic.List<t_AI> _dataList;
    
    public Data_AI(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, t_AI>();
        _dataList = new System.Collections.Generic.List<t_AI>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            t_AI _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = t_AI.Deserializet_AI(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, t_AI> DataMap => _dataMap;
    public System.Collections.Generic.List<t_AI> DataList => _dataList;

    public t_AI GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public t_AI Get(int key) => _dataMap[key];
    public t_AI this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

