
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 道具表
/// </summary>
public partial class Data_Item
{
    private readonly System.Collections.Generic.Dictionary<int, t_Item> _dataMap;
    private readonly System.Collections.Generic.List<t_Item> _dataList;
    
    public Data_Item(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, t_Item>();
        _dataList = new System.Collections.Generic.List<t_Item>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            t_Item _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = t_Item.Deserializet_Item(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, t_Item> DataMap => _dataMap;
    public System.Collections.Generic.List<t_Item> DataList => _dataList;

    public t_Item GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public t_Item Get(int key) => _dataMap[key];
    public t_Item this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

