
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 装备
/// </summary>
public partial class Data_Equip
{
    private readonly System.Collections.Generic.Dictionary<int, t_Equip> _dataMap;
    private readonly System.Collections.Generic.List<t_Equip> _dataList;
    
    public Data_Equip(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, t_Equip>();
        _dataList = new System.Collections.Generic.List<t_Equip>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            t_Equip _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = t_Equip.Deserializet_Equip(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, t_Equip> DataMap => _dataMap;
    public System.Collections.Generic.List<t_Equip> DataList => _dataList;

    public t_Equip GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public t_Equip Get(int key) => _dataMap[key];
    public t_Equip this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

