
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 技能表
/// </summary>
public partial class Data_Ability
{
    private readonly System.Collections.Generic.Dictionary<int, t_Ability> _dataMap;
    private readonly System.Collections.Generic.List<t_Ability> _dataList;
    
    public Data_Ability(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, t_Ability>();
        _dataList = new System.Collections.Generic.List<t_Ability>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            t_Ability _v;
            _v = t_Ability.Deserializet_Ability(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, t_Ability> DataMap => _dataMap;
    public System.Collections.Generic.List<t_Ability> DataList => _dataList;

    public t_Ability GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public t_Ability Get(int key) => _dataMap[key];
    public t_Ability this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

