
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 掉落表
/// </summary>
public partial class Data_Drop
{
    private readonly System.Collections.Generic.Dictionary<int, t_Drop> _dataMap;
    private readonly System.Collections.Generic.List<t_Drop> _dataList;
    
    public Data_Drop(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, t_Drop>();
        _dataList = new System.Collections.Generic.List<t_Drop>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            t_Drop _v;
            _v = t_Drop.Deserializet_Drop(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.DropId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, t_Drop> DataMap => _dataMap;
    public System.Collections.Generic.List<t_Drop> DataList => _dataList;

    public t_Drop GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public t_Drop Get(int key) => _dataMap[key];
    public t_Drop this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

