
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 单位表
/// </summary>
public partial class Data_Entities
{
    private readonly System.Collections.Generic.Dictionary<int, t_Entity> _dataMap;
    private readonly System.Collections.Generic.List<t_Entity> _dataList;
    
    public Data_Entities(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, t_Entity>();
        _dataList = new System.Collections.Generic.List<t_Entity>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            t_Entity _v;
            _v = t_Entity.Deserializet_Entity(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, t_Entity> DataMap => _dataMap;
    public System.Collections.Generic.List<t_Entity> DataList => _dataList;

    public t_Entity GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public t_Entity Get(int key) => _dataMap[key];
    public t_Entity this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

