
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 普通型
/// </summary>
public sealed partial class DefaultParams : AiStrategyParams
{
    public DefaultParams(ByteBuf _buf)  : base(_buf) 
    {
        ChaseTiredDuration = _buf.ReadInt();
    }

    public static DefaultParams DeserializeDefaultParams(ByteBuf _buf)
    {
        return new DefaultParams(_buf);
    }

    /// <summary>
    /// 追击疲惫回合
    /// </summary>
    public readonly int ChaseTiredDuration;
   
    public const int __ID__ = 1669297927;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ChaseTiredDuration:" + ChaseTiredDuration + ","
        + "}";
    }
}

}

