
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Drop : Luban.BeanBase
{
    public Drop(JSONNode _buf) 
    {
        { if(!_buf["item_id"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { if(!_buf["min"].IsNumber) { throw new SerializationException(); }  Min = _buf["min"]; }
        { if(!_buf["max"].IsNumber) { throw new SerializationException(); }  Max = _buf["max"]; }
        { if(!_buf["chance"].IsNumber) { throw new SerializationException(); }  Chance = _buf["chance"]; }
    }

    public static Drop DeserializeDrop(JSONNode _buf)
    {
        return new Drop(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Min;
    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Max;
    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Chance;
   
    public const int __ID__ = 2138895;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "min:" + Min + ","
        + "max:" + Max + ","
        + "chance:" + Chance + ","
        + "}";
    }
}

}

