
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Drop : Luban.BeanBase
{
    public Drop(ByteBuf _buf) 
    {
        ItemId = _buf.ReadInt();
        Min = _buf.ReadInt();
        Max = _buf.ReadInt();
        Chance = _buf.ReadInt();
    }

    public static Drop DeserializeDrop(ByteBuf _buf)
    {
        return new Drop(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Min;
    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Max;
    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Chance;
   
    public const int __ID__ = 2138895;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "min:" + Min + ","
        + "max:" + Max + ","
        + "chance:" + Chance + ","
        + "}";
    }
}

}

