
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EntityType
    {
        /// <summary>
        /// 玩家模板
        /// </summary>
        PLAYER = 1,
        /// <summary>
        /// 敌方模板
        /// </summary>
        ENEMY = 2,
        /// <summary>
        /// 中立
        /// </summary>
        NEUTRAL = 3,
        /// <summary>
        /// NPC模板
        /// </summary>
        NPC = 4,
    }

} 

