
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 装备类型
    /// </summary>
    public enum EquipType
    {
        /// <summary>
        /// 主手
        /// </summary>
        HandMain = 0,
        /// <summary>
        /// 副手
        /// </summary>
        HandOff = 1,
        /// <summary>
        /// 头盔
        /// </summary>
        Helmet = 2,
        /// <summary>
        /// 护甲
        /// </summary>
        Armor = 3,
        /// <summary>
        /// 护腿
        /// </summary>
        Greaves = 4,
        /// <summary>
        /// 鞋子
        /// </summary>
        Boots = 5,
        /// <summary>
        /// 戒指
        /// </summary>
        Ring = 6,
        /// <summary>
        /// 项链
        /// </summary>
        Necklace = 7,
    }

} 

