
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 装备类型
    /// </summary>
    public enum EquipType
    {
        /// <summary>
        /// 武器
        /// </summary>
        Weapon = 0,
        /// <summary>
        /// 头盔
        /// </summary>
        Helmet = 1,
        /// <summary>
        /// 面具
        /// </summary>
        Mask = 2,
        /// <summary>
        /// 护甲
        /// </summary>
        Armor = 3,
        /// <summary>
        /// 鞋子
        /// </summary>
        Boots = 4,
    }

} 

