
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum ItemType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 普通道具
        /// </summary>
        Generic = 1,
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumable = 2,
        /// <summary>
        /// 装备
        /// </summary>
        Equipment = 3,
        /// <summary>
        /// 任务道具
        /// </summary>
        Quest = 4,
        /// <summary>
        /// 材料
        /// </summary>
        Material = 5,
    }

} 

