
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 道具品质
    /// </summary>
    public enum ItemRarity
    {
        /// <summary>
        /// 普通
        /// </summary>
        Common = 0,
        /// <summary>
        /// 精良
        /// </summary>
        Uncommon = 1,
        /// <summary>
        /// 紫
        /// </summary>
        Rare = 2,
        /// <summary>
        /// 橙
        /// </summary>
        Epic = 3,
        /// <summary>
        /// 彩色
        /// </summary>
        Mythic = 4,
        /// <summary>
        /// 红
        /// </summary>
        Cursed = 5,
    }

} 

