
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 召唤物1
/// </summary>
public sealed partial class Summon1Params : AiStrategyParams
{
    public Summon1Params(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["FollowDistance"].IsNumber) { throw new SerializationException(); }  FollowDistance = _buf["FollowDistance"]; }
    }

    public static Summon1Params DeserializeSummon1Params(JSONNode _buf)
    {
        return new Summon1Params(_buf);
    }

    /// <summary>
    /// 跟随主人距离
    /// </summary>
    public readonly int FollowDistance;
   
    public const int __ID__ = -606102282;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "FollowDistance:" + FollowDistance + ","
        + "}";
    }
}

}

