
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 道具
/// </summary>
public sealed partial class t_Ability : Luban.BeanBase
{
    public t_Ability(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Addressable = _buf.ReadString();
    }

    public static t_Ability Deserializet_Ability(ByteBuf _buf)
    {
        return new t_Ability(_buf);
    }

    /// <summary>
    /// 技能id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 地址
    /// </summary>
    public readonly string Addressable;
   
    public const int __ID__ = -683917249;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "addressable:" + Addressable + ","
        + "}";
    }
}

}

