
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// AI类
/// </summary>
public sealed partial class t_AI : Luban.BeanBase
{
    public t_AI(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["aiParamsBase"].IsObject) { throw new SerializationException(); }  AiParamsBase = AiParamsBase.DeserializeAiParamsBase(_buf["aiParamsBase"]);  }
        { if(!_buf["aiPattern"].IsNumber) { throw new SerializationException(); }  AiPattern = (AiPattern)_buf["aiPattern"].AsInt; }
        { if(!_buf["strategyParams"].IsObject) { throw new SerializationException(); }  StrategyParams = AiStrategyParams.DeserializeAiStrategyParams(_buf["strategyParams"]);  }
    }

    public static t_AI Deserializet_AI(JSONNode _buf)
    {
        return new t_AI(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    public readonly AiParamsBase AiParamsBase;
    public readonly AiPattern AiPattern;
    public readonly AiStrategyParams StrategyParams;
   
    public const int __ID__ = 3549139;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        AiParamsBase?.ResolveRef(tables);
        StrategyParams?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "aiParamsBase:" + AiParamsBase + ","
        + "aiPattern:" + AiPattern + ","
        + "strategyParams:" + StrategyParams + ","
        + "}";
    }
}

}

