
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 道具
/// </summary>
public sealed partial class t_Drop : Luban.BeanBase
{
    public t_Drop(ByteBuf _buf) 
    {
        DropId = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Drops = new System.Collections.Generic.List<Drop>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Drop _e0;  _e0 = Drop.DeserializeDrop(_buf); Drops.Add(_e0);}}
    }

    public static t_Drop Deserializet_Drop(ByteBuf _buf)
    {
        return new t_Drop(_buf);
    }

    /// <summary>
    /// 掉落ID
    /// </summary>
    public readonly int DropId;
    /// <summary>
    /// 掉落列表
    /// </summary>
    public readonly System.Collections.Generic.List<Drop> Drops;
   
    public const int __ID__ = -884112390;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Drops) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "dropId:" + DropId + ","
        + "drops:" + Luban.StringUtil.CollectionToString(Drops) + ","
        + "}";
    }
}

}

