
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 道具
/// </summary>
public sealed partial class t_Drop : Luban.BeanBase
{
    public t_Drop(JSONNode _buf) 
    {
        { if(!_buf["drop_id"].IsNumber) { throw new SerializationException(); }  DropId = _buf["drop_id"]; }
        { if(!_buf["darity"].IsNumber) { throw new SerializationException(); }  Darity = _buf["darity"]; }
        { var __json0 = _buf["drops"]; if(!__json0.IsArray) { throw new SerializationException(); } Drops = new System.Collections.Generic.List<Drop>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Drop __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Drop.DeserializeDrop(__e0);  }  Drops.Add(__v0); }   }
    }

    public static t_Drop Deserializet_Drop(JSONNode _buf)
    {
        return new t_Drop(_buf);
    }

    /// <summary>
    /// 掉落ID
    /// </summary>
    public readonly int DropId;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Darity;
    /// <summary>
    /// 掉落列表
    /// </summary>
    public readonly System.Collections.Generic.List<Drop> Drops;
   
    public const int __ID__ = -884112390;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Drops) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "dropId:" + DropId + ","
        + "darity:" + Darity + ","
        + "drops:" + Luban.StringUtil.CollectionToString(Drops) + ","
        + "}";
    }
}

}

