
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 道具
/// </summary>
public sealed partial class t_Entity : Luban.BeanBase
{
    public t_Entity(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsNumber) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsNumber) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (EntityType)_buf["type"].AsInt; }
        { if(!_buf["addressable"].IsString) { throw new SerializationException(); }  Addressable = _buf["addressable"]; }
        { if(!_buf["attr"].IsObject) { throw new SerializationException(); }  Attr = Defination.Attribute.DeserializeAttribute(_buf["attr"]);  }
        { var __json0 = _buf["abilities"]; if(!__json0.IsArray) { throw new SerializationException(); } Abilities = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Abilities.Add(__v0); }   }
        { var _j = _buf["drop_id"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  DropId = _j; } } else { DropId = null; } }
        { var _j = _buf["ai_id"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  AiId = _j; } } else { AiId = null; } }
    }

    public static t_Entity Deserializet_Entity(JSONNode _buf)
    {
        return new t_Entity(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    public readonly int Name;
    public readonly int Desc;
    public readonly EntityType Type;
    public readonly string Addressable;
    public readonly Defination.Attribute Attr;
    /// <summary>
    /// 技能列表(资源地址)
    /// </summary>
    public readonly System.Collections.Generic.List<string> Abilities;
    /// <summary>
    /// 掉落
    /// </summary>
    public readonly int? DropId;
    /// <summary>
    /// AI ID
    /// </summary>
    public readonly int? AiId;
   
    public const int __ID__ = 796598830;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Attr?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "addressable:" + Addressable + ","
        + "attr:" + Attr + ","
        + "abilities:" + Luban.StringUtil.CollectionToString(Abilities) + ","
        + "dropId:" + DropId + ","
        + "aiId:" + AiId + ","
        + "}";
    }
}

}

