
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 道具
/// </summary>
public sealed partial class t_Entity : Luban.BeanBase
{
    public t_Entity(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadInt();
        Desc = _buf.ReadInt();
        Type = (EntityType)_buf.ReadInt();
        Addressable = _buf.ReadString();
        Attr = Defination.Attribute.DeserializeAttribute(_buf);
        if(_buf.ReadBool()){ DropId = _buf.ReadInt(); } else { DropId = null; }
    }

    public static t_Entity Deserializet_Entity(ByteBuf _buf)
    {
        return new t_Entity(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    public readonly int Name;
    public readonly int Desc;
    public readonly EntityType Type;
    public readonly string Addressable;
    public readonly Defination.Attribute Attr;
    /// <summary>
    /// 掉落
    /// </summary>
    public readonly int? DropId;
   
    public const int __ID__ = 796598830;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Attr?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "addressable:" + Addressable + ","
        + "attr:" + Attr + ","
        + "dropId:" + DropId + ","
        + "}";
    }
}

}

