
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 装备
/// </summary>
public sealed partial class t_Equip : t_ItemBase
{
    public t_Equip(ByteBuf _buf)  : base(_buf) 
    {
        EquipType = (EquipType)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Modifier = new System.Collections.Generic.List<Defination.AttributeModifier>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Defination.AttributeModifier _e0;  _e0 = Defination.AttributeModifier.DeserializeAttributeModifier(_buf); Modifier.Add(_e0);}}
    }

    public static t_Equip Deserializet_Equip(ByteBuf _buf)
    {
        return new t_Equip(_buf);
    }

    public readonly EquipType EquipType;
    public readonly System.Collections.Generic.List<Defination.AttributeModifier> Modifier;
   
    public const int __ID__ = -1636780923;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        foreach (var _e in Modifier) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "category:" + Category + ","
        + "type:" + Type + ","
        + "rarity:" + Rarity + ","
        + "icon:" + Icon + ","
        + "stackable:" + Stackable + ","
        + "tradeValue:" + TradeValue + ","
        + "prefab:" + Prefab + ","
        + "equipType:" + EquipType + ","
        + "Modifier:" + Luban.StringUtil.CollectionToString(Modifier) + ","
        + "}";
    }
}

}

