
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 装备
/// </summary>
public sealed partial class t_Equip : t_ItemBase
{
    public t_Equip(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["equipType"].IsNumber) { throw new SerializationException(); }  EquipType = (EquipType)_buf["equipType"].AsInt; }
    }

    public static t_Equip Deserializet_Equip(JSONNode _buf)
    {
        return new t_Equip(_buf);
    }

    public readonly EquipType EquipType;
   
    public const int __ID__ = -1636780923;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "rarity:" + Rarity + ","
        + "icon:" + Icon + ","
        + "stackable:" + Stackable + ","
        + "tradeValue:" + TradeValue + ","
        + "x:" + X + ","
        + "y:" + Y + ","
        + "prefab:" + Prefab + ","
        + "equipType:" + EquipType + ","
        + "}";
    }
}

}

