
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 道具基类
/// </summary>
public abstract partial class t_ItemBase : Luban.BeanBase
{
    public t_ItemBase(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsNumber) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsNumber) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (ItemType)_buf["type"].AsInt; }
        { if(!_buf["rarity"].IsNumber) { throw new SerializationException(); }  Rarity = (ItemRarity)_buf["rarity"].AsInt; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["stackable"].IsBoolean) { throw new SerializationException(); }  Stackable = _buf["stackable"]; }
        { if(!_buf["tradeValue"].IsNumber) { throw new SerializationException(); }  TradeValue = _buf["tradeValue"]; }
        { if(!_buf["x"].IsNumber) { throw new SerializationException(); }  X = _buf["x"]; }
        { if(!_buf["y"].IsNumber) { throw new SerializationException(); }  Y = _buf["y"]; }
    }

    public static t_ItemBase Deserializet_ItemBase(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "t_Equip": return new t_Equip(_buf);
            case "t_Item": return new t_Item(_buf);
            default: throw new SerializationException();
        }
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    public readonly int Name;
    public readonly int Desc;
    public readonly ItemType Type;
    public readonly ItemRarity Rarity;
    public readonly string Icon;
    public readonly bool Stackable;
    public readonly int TradeValue;
    /// <summary>
    /// 水平占格
    /// </summary>
    public readonly int X;
    /// <summary>
    /// 竖直占格
    /// </summary>
    public readonly int Y;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "rarity:" + Rarity + ","
        + "icon:" + Icon + ","
        + "stackable:" + Stackable + ","
        + "tradeValue:" + TradeValue + ","
        + "x:" + X + ","
        + "y:" + Y + ","
        + "}";
    }
}

}

