
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 道具类
/// </summary>
public sealed partial class t_Item : t_ItemBase
{
    public t_Item(JSONNode _buf)  : base(_buf) 
    {
    }

    public static t_Item Deserializet_Item(JSONNode _buf)
    {
        return new t_Item(_buf);
    }

   
    public const int __ID__ = -883961826;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "rarity:" + Rarity + ","
        + "icon:" + Icon + ","
        + "stackable:" + Stackable + ","
        + "tradeValue:" + TradeValue + ","
        + "prefab:" + Prefab + ","
        + "}";
    }
}

}

