
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 道具基类
/// </summary>
public abstract partial class t_ItemBase : Luban.BeanBase
{
    public t_ItemBase(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Category = _buf.ReadString();
        Desc = _buf.ReadString();
        Type = (ItemType)_buf.ReadInt();
        Rarity = (ItemRarity)_buf.ReadInt();
        Icon = _buf.ReadString();
        Stackable = _buf.ReadBool();
        TradeValue = _buf.ReadInt();
        if(_buf.ReadBool()){ Prefab = _buf.ReadString(); } else { Prefab = null; }
    }

    public static t_ItemBase Deserializet_ItemBase(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case t_Equip.__ID__: return new t_Equip(_buf);
            case t_Item.__ID__: return new t_Item(_buf);
            default: throw new SerializationException();
        }
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    public readonly string Name;
    public readonly string Category;
    public readonly string Desc;
    public readonly ItemType Type;
    public readonly ItemRarity Rarity;
    public readonly string Icon;
    public readonly bool Stackable;
    public readonly int TradeValue;
    public readonly string Prefab;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "category:" + Category + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "rarity:" + Rarity + ","
        + "icon:" + Icon + ","
        + "stackable:" + Stackable + ","
        + "tradeValue:" + TradeValue + ","
        + "prefab:" + Prefab + ","
        + "}";
    }
}

}

