
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 道具
/// </summary>
public sealed partial class t_LevelUp : Luban.BeanBase
{
    public t_LevelUp(ByteBuf _buf) 
    {
        Level = _buf.ReadInt();
        Exp = _buf.ReadInt();
    }

    public static t_LevelUp Deserializet_LevelUp(ByteBuf _buf)
    {
        return new t_LevelUp(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// Exp
    /// </summary>
    public readonly int Exp;
   
    public const int __ID__ = 586375252;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "exp:" + Exp + ","
        + "}";
    }
}

}

