
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 技能表
    /// </summary>
    public Data_Ability DataAbility {get; }
    /// <summary>
    /// 掉落表
    /// </summary>
    public Data_Drop DataDrop {get; }
    /// <summary>
    /// 单位表
    /// </summary>
    public Data_Entities DataEntities {get; }
    /// <summary>
    /// 装备
    /// </summary>
    public Data_Equip DataEquip {get; }
    /// <summary>
    /// 道具表
    /// </summary>
    public Data_Item DataItem {get; }
    /// <summary>
    /// 等级表
    /// </summary>
    public Data_LevelUp DataLevelUp {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        DataAbility = new Data_Ability(loader("data_ability"));
        DataDrop = new Data_Drop(loader("data_drop"));
        DataEntities = new Data_Entities(loader("data_entities"));
        DataEquip = new Data_Equip(loader("data_equip"));
        DataItem = new Data_Item(loader("data_item"));
        DataLevelUp = new Data_LevelUp(loader("data_levelup"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        DataAbility.ResolveRef(this);
        DataDrop.ResolveRef(this);
        DataEntities.ResolveRef(this);
        DataEquip.ResolveRef(this);
        DataItem.ResolveRef(this);
        DataLevelUp.ResolveRef(this);
    }
}

}
