
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 掉落表
    /// </summary>
    public Data_Drop DataDrop {get; }
    /// <summary>
    /// 单位表
    /// </summary>
    public Data_Entitys DataEntitys {get; }
    /// <summary>
    /// 装备
    /// </summary>
    public Data_Equip DataEquip {get; }
    /// <summary>
    /// 道具表
    /// </summary>
    public Data_Item DataItem {get; }
    /// <summary>
    /// AI表
    /// </summary>
    public Data_AI DataAI {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        DataDrop = new Data_Drop(loader("data_drop"));
        DataEntitys = new Data_Entitys(loader("data_entitys"));
        DataEquip = new Data_Equip(loader("data_equip"));
        DataItem = new Data_Item(loader("data_item"));
        DataAI = new Data_AI(loader("data_ai"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        DataDrop.ResolveRef(this);
        DataEntitys.ResolveRef(this);
        DataEquip.ResolveRef(this);
        DataItem.ResolveRef(this);
        DataAI.ResolveRef(this);
    }
}

}
