
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Defination
{
/// <summary>
/// 属性
/// </summary>
public sealed partial class Attribute : Luban.BeanBase
{
    public Attribute(JSONNode _buf) 
    {
        { if(!_buf["BaseAttack"].IsNumber) { throw new SerializationException(); }  BaseAttack = _buf["BaseAttack"]; }
        { if(!_buf["Strength"].IsNumber) { throw new SerializationException(); }  Strength = _buf["Strength"]; }
        { if(!_buf["Dexterity"].IsNumber) { throw new SerializationException(); }  Dexterity = _buf["Dexterity"]; }
        { if(!_buf["Intelligence"].IsNumber) { throw new SerializationException(); }  Intelligence = _buf["Intelligence"]; }
        { if(!_buf["Vitality"].IsNumber) { throw new SerializationException(); }  Vitality = _buf["Vitality"]; }
        { if(!_buf["Health"].IsNumber) { throw new SerializationException(); }  Health = _buf["Health"]; }
        { if(!_buf["Mana"].IsNumber) { throw new SerializationException(); }  Mana = _buf["Mana"]; }
        { if(!_buf["CritChance"].IsNumber) { throw new SerializationException(); }  CritChance = _buf["CritChance"]; }
        { if(!_buf["CritMultiplier"].IsNumber) { throw new SerializationException(); }  CritMultiplier = _buf["CritMultiplier"]; }
        { if(!_buf["Armor"].IsNumber) { throw new SerializationException(); }  Armor = _buf["Armor"]; }
        { if(!_buf["MagicResist"].IsNumber) { throw new SerializationException(); }  MagicResist = _buf["MagicResist"]; }
        { if(!_buf["ArmorPenetration"].IsNumber) { throw new SerializationException(); }  ArmorPenetration = _buf["ArmorPenetration"]; }
        { if(!_buf["MagicPenetration"].IsNumber) { throw new SerializationException(); }  MagicPenetration = _buf["MagicPenetration"]; }
        { if(!_buf["Dodge"].IsNumber) { throw new SerializationException(); }  Dodge = _buf["Dodge"]; }
    }

    public static Attribute DeserializeAttribute(JSONNode _buf)
    {
        return new Defination.Attribute(_buf);
    }

    /// <summary>
    /// BaseAttack: BaseAttack of character without weapon.
    /// </summary>
    public readonly int BaseAttack;
    /// <summary>
    /// STR: Physical damage, armor bonus
    /// </summary>
    public readonly int Strength;
    /// <summary>
    /// DEX/AGI: Crit chance, attack speed, dodge
    /// </summary>
    public readonly int Dexterity;
    /// <summary>
    /// INT: Magic damage, mana
    /// </summary>
    public readonly int Intelligence;
    /// <summary>
    /// VIT: Health, defense
    /// </summary>
    public readonly int Vitality;
    /// <summary>
    /// Max HP
    /// </summary>
    public readonly int Health;
    /// <summary>
    /// Max MP
    /// </summary>
    public readonly int Mana;
    /// <summary>
    /// Raw % (0.05f = 5%)
    /// </summary>
    public readonly int CritChance;
    /// <summary>
    /// 1.5f = 150% crit dmg
    /// </summary>
    public readonly int CritMultiplier;
    /// <summary>
    /// Armor
    /// </summary>
    public readonly int Armor;
    /// <summary>
    /// MagicResist
    /// </summary>
    public readonly int MagicResist;
    /// <summary>
    /// 物穿
    /// </summary>
    public readonly int ArmorPenetration;
    /// <summary>
    /// 法穿
    /// </summary>
    public readonly int MagicPenetration;
    /// <summary>
    /// 闪避率（百分比）
    /// </summary>
    public readonly int Dodge;
   
    public const int __ID__ = -439948871;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BaseAttack:" + BaseAttack + ","
        + "Strength:" + Strength + ","
        + "Dexterity:" + Dexterity + ","
        + "Intelligence:" + Intelligence + ","
        + "Vitality:" + Vitality + ","
        + "Health:" + Health + ","
        + "Mana:" + Mana + ","
        + "CritChance:" + CritChance + ","
        + "CritMultiplier:" + CritMultiplier + ","
        + "Armor:" + Armor + ","
        + "MagicResist:" + MagicResist + ","
        + "ArmorPenetration:" + ArmorPenetration + ","
        + "MagicPenetration:" + MagicPenetration + ","
        + "Dodge:" + Dodge + ","
        + "}";
    }
}

}

