
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Defination
{
/// <summary>
/// 属性
/// </summary>
public sealed partial class Attribute : Luban.BeanBase
{
    public Attribute(ByteBuf _buf) 
    {
        BaseAttack = _buf.ReadInt();
        Strength = _buf.ReadInt();
        Dexterity = _buf.ReadInt();
        Intelligence = _buf.ReadInt();
        Vitality = _buf.ReadInt();
        Health = _buf.ReadInt();
        Mana = _buf.ReadInt();
        CritChance = _buf.ReadInt();
        CritMultiplier = _buf.ReadInt();
        Armor = _buf.ReadInt();
        MagicResist = _buf.ReadInt();
        ArmorPenetration = _buf.ReadInt();
        MagicPenetration = _buf.ReadInt();
        Dodge = _buf.ReadInt();
    }

    public static Attribute DeserializeAttribute(ByteBuf _buf)
    {
        return new Defination.Attribute(_buf);
    }

    /// <summary>
    /// BaseAttack: BaseAttack of character without weapon.
    /// </summary>
    public readonly int BaseAttack;
    /// <summary>
    /// STR: Physical damage, armor bonus
    /// </summary>
    public readonly int Strength;
    /// <summary>
    /// DEX/AGI: Crit chance, attack speed, dodge
    /// </summary>
    public readonly int Dexterity;
    /// <summary>
    /// INT: Magic damage, mana
    /// </summary>
    public readonly int Intelligence;
    /// <summary>
    /// VIT: Health, defense
    /// </summary>
    public readonly int Vitality;
    /// <summary>
    /// Max HP
    /// </summary>
    public readonly int Health;
    /// <summary>
    /// Max MP
    /// </summary>
    public readonly int Mana;
    /// <summary>
    /// Raw % (0.05f = 5%)
    /// </summary>
    public readonly int CritChance;
    /// <summary>
    /// 1.5f = 150% crit dmg
    /// </summary>
    public readonly int CritMultiplier;
    /// <summary>
    /// Armor
    /// </summary>
    public readonly int Armor;
    /// <summary>
    /// MagicResist
    /// </summary>
    public readonly int MagicResist;
    /// <summary>
    /// 物穿
    /// </summary>
    public readonly int ArmorPenetration;
    /// <summary>
    /// 法穿
    /// </summary>
    public readonly int MagicPenetration;
    /// <summary>
    /// 闪避率（百分比）
    /// </summary>
    public readonly int Dodge;
   
    public const int __ID__ = -439948871;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BaseAttack:" + BaseAttack + ","
        + "Strength:" + Strength + ","
        + "Dexterity:" + Dexterity + ","
        + "Intelligence:" + Intelligence + ","
        + "Vitality:" + Vitality + ","
        + "Health:" + Health + ","
        + "Mana:" + Mana + ","
        + "CritChance:" + CritChance + ","
        + "CritMultiplier:" + CritMultiplier + ","
        + "Armor:" + Armor + ","
        + "MagicResist:" + MagicResist + ","
        + "ArmorPenetration:" + ArmorPenetration + ","
        + "MagicPenetration:" + MagicPenetration + ","
        + "Dodge:" + Dodge + ","
        + "}";
    }
}

}

