
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Defination
{
/// <summary>
/// 属性修改器
/// </summary>
public sealed partial class AttributeModifier : Luban.BeanBase
{
    public AttributeModifier(ByteBuf _buf) 
    {
        T = (Defination.AttributeType)_buf.ReadInt();
        M = (Defination.AttributeModifierType)_buf.ReadInt();
        V = _buf.ReadInt();
    }

    public static AttributeModifier DeserializeAttributeModifier(ByteBuf _buf)
    {
        return new Defination.AttributeModifier(_buf);
    }

    /// <summary>
    /// 加成目标
    /// </summary>
    public readonly Defination.AttributeType T;
    /// <summary>
    /// 加成类型
    /// </summary>
    public readonly Defination.AttributeModifierType M;
    /// <summary>
    /// 加成数值
    /// </summary>
    public readonly int V;
   
    public const int __ID__ = 225216432;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "T:" + T + ","
        + "M:" + M + ","
        + "V:" + V + ","
        + "}";
    }
}

}

