
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Defination
{ 
    /// <summary>
    /// 属性类型
    /// </summary>
    public enum AttributeType
    {
        /// <summary>
        /// BaseAttack: BaseAttack of character without weapon.
        /// </summary>
        BaseAttack = 0,
        /// <summary>
        /// STR: Physical damage, armor bonus
        /// </summary>
        Strength = 1,
        /// <summary>
        /// DEX/AGI: Crit chance, attack speed, dodge
        /// </summary>
        Dexterity = 2,
        /// <summary>
        /// INT: Magic damage, mana
        /// </summary>
        Intelligence = 3,
        /// <summary>
        /// VIT: Health, defense
        /// </summary>
        Vitality = 4,
        /// <summary>
        /// Max HP
        /// </summary>
        Health = 5,
        /// <summary>
        /// Max MP
        /// </summary>
        Mana = 6,
        /// <summary>
        /// Raw % (0.05f = 5%)
        /// </summary>
        CritChance = 7,
        /// <summary>
        /// 1.5f = 150% crit dmg
        /// </summary>
        CritMultiplier = 8,
        /// <summary>
        /// Armor
        /// </summary>
        Armor = 9,
        /// <summary>
        /// MagicResist
        /// </summary>
        MagicResist = 10,
        /// <summary>
        /// 物穿
        /// </summary>
        ArmorPenetration = 11,
        /// <summary>
        /// 法穿
        /// </summary>
        MagicPenetration = 12,
        /// <summary>
        /// 闪避率（百分比）
        /// </summary>
        Dodge = 13,
    }

} 

