
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Defination
{ 
    /// <summary>
    /// 属性类型
    /// </summary>
    public enum AttributeModifierType
    {
        /// <summary>
        /// 加基础
        /// </summary>
        AddFlat = 0,
        /// <summary>
        /// 加算百分比(1 + 10% + 10%).
        /// </summary>
        AddPercent = 1,
        /// <summary>
        /// 乘算百分比1 * (1 + 10%) * (1 + 10%).
        /// </summary>
        MulPercent = 2,
        /// <summary>
        /// 加最终值
        /// </summary>
        AddTotal = 3,
    }

} 

